import FormInput from '../src/components/form/index'
import styles from "../styles/Home.module.css";
import Head from "next/head";
import {Layout} from "antd";
import HeaderComponent from "../src/components/typography/header";
import {DEFAULT_HEADER, DEFAULT_TEXT} from "../public/constant";
import ParagraphComp from "../src/components/typography/paragragh";
import Button from "../src/components/button";
import React from "react";
const {  Footer } = Layout;

export default function Adds ()  {
    return (

        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Layout style={{minWidth: 400, maxHeight:400}}>
                    <FormInput/>
                </Layout>
            </main>

            <footer className={styles.footer}>
                <a>Hello world Footer</a>
            </footer>
        </div>
    )
}