import  TableComponent  from '../src/components/table/index'
import styles from "../styles/Home.module.css";
import Head from "next/head";
import {Layout} from "antd";
import ListsAllCitiesAndTowns from '../src/container/listsAllCitiesAndTowns/index'
import Button from "../src/components/button";
const {  Footer } = Layout;

export default function Lists ()  {
    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <Layout>
                    <ListsAllCitiesAndTowns/>

                    <Footer style={{display:'flex', justifyContent: 'space-around'}}>
                        <Button backgroundColor={"#4A5D6D"} size={'large'}  content={'Adds'} to={'adds'}/>
                    </Footer>
                </Layout>
            </main>

            <footer className={styles.footer}>
                <a>Hello world Footer</a>
            </footer>
        </div>
    )
}